# Generated by Django 3.0.4 on 2020-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('original_publication_year', models.TextField(blank=True, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('language_code', models.TextField(blank=True, null=True)),
                ('average_rating', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField(unique=True)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
