# Generated by Django 3.0.4 on 2020-03-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_report', '0002_auto_20200313_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_report.books'),
        ),
    ]
