# Generated by Django 3.0.4 on 2020-03-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_report', '0004_test_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
        migrations.AlterModelTable(
            name='ratings',
            table='ratings',
        ),
    ]
