# Generated by Django 3.0.4 on 2020-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_report', '0005_auto_20200316_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
