# Generated by Django 3.0.4 on 2020-03-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_report', '0007_auto_20200317_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ratings',
        ),
    ]
